### ISSUE TITLE
Can I add Koumbit.org to the list?

### ISSUE THREAD

**Issue by sebas891** [libresh/awesome-librehosters#22]
Hi folks,

Can I add Koumbit.org to the list? I could not find a grid of analysis in our documentation but yes we offer solidarity hosting and we only use freesoftware!

Cheers,

Sébastien
part of the worker's collective at Koumbit

**Comment by pierreozoux** [comment]
Yes, please PR :)

**Comment by almereyda** [comment]
@sebas891 I am sorry I forgot to add you after my visit to Montréal two years ago! Great work you are doing with Remix the Commons. Greetings to Y.O. and the whole ##foulab crowd.
