### ISSUE TITLE
Make a proposal to Commons partners

### ISSUE THREAD

**Issue by almereyda** [libresh/awesome-librehosters#6]
Our friends from Encommuns will run a shared server at Online.net

https://fr.liberapay.com/LegalServiceforCommons_Org/

Can we make another offer?

**Comment by pierreozoux** [comment]
A joint venture EcoBytes/IH? Go for it :) Good idea :)

**Comment by almereyda** [comment]
I would combine this with offering stewardship of the `transformap.co(op)` domains, as it is still owned by me personally.

**Comment by pierreozoux** [comment]
Please be specific, I don't understand what you are saying. And is it the right place to discuss that matter?

**Comment by almereyda** [comment]
The statement above was a note to myself which reflected the fact of outsourcing domain ownership for Commons Infrastructure we are hosting.

These should be bound to a trustable third party escrow service like LSC-L1 introduced above.

**Comment by pierreozoux** [comment]
Ok, got it :) But I would need to trust it :)

I prefer to be conservative on that and have 2 people I trust more than a 3rd party which I don't know.

**Comment by pierreozoux** [comment]
Did you contact them?

**Comment by almereyda** [comment]
This is now superseded by https://framagit.org/librehosters/declaration
